# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b43c182d2fa436d6bc98590c09e325a20ac0e172a41ac1fc2e0c72711881368bfef9d13c8d1bc15628fda9ef30e750d89e1b06ab7b4cfc7dcbe4c70ef353acc2

test:
  secret_key_base: 316b6b41e19db7886532787cc9cbb10208ecd199aa8ef72b08452666670bd4541dc6e18e845ddc0b59b936f6476881f074383007da365a9d6cb28be2596ebc1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
